# helmfile version v1.1.7
# helm plugin install https://github.com/aslafy-z/helm-git --version 1.4.1
releases:
  - name: sharepoint-connector
    chart: git+https://github.com/Unique-AG/connectors@services/sharepoint-connector/deploy/helm-charts/sharepoint-connector?ref=sharepoint-connector@v2.0.0-alpha.10&depupdate=1
    namespace: sharepoint-connector
    values:
      - values.yaml
