# helmfile version v1.1.7
# helm plugin install https://github.com/aslafy-z/helm-git --version 1.4.1
repositories:
  - name: spc
    url: git+https://github.com/Unique-AG/connectors@services/sharepoint-connector/deploy/helm-charts?ref=sharepoint-connector@v2.0.0-alpha.10&depupdate=1

releases:
  - name: sharepoint-connector
    chart: spc/sharepoint-connector
    version: 2.0.0-alpha.10
    namespace: sharepoint-connector
    values:
      - values.yaml
