apiVersion: v2
name: teams-mcp
description: An experimental MCP server for Teams leveraging the Microsoft Graph API.
type: application
version: 0.2.6
appVersion: 0.2.6
dependencies:
  - alias: server
    name: backend-service
    repository: oci://ghcr.io/unique-ag/helm-charts
    version: ~8.2.0
