connector:
  networkPolicy:
    ingress:
      - from:
          - podSelector:
              matchLabels:
                app.kubernetes.io/managed-by: prometheus-operator
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: system
  prometheus:
    defaultAlerts:
      additionalLabels:
        team: my-team
  serviceAccount:
    workloadIdentity:
      clientId: 00000000-0000-0000-0000-000000000000
  # Secret only added for testing and demonstration (certificate for SharePoint auth)
  extraObjects:
    - apiVersion: v1
    - kind: Secret
      metadata:
        name: sharepoint-connector-secret
      type: Opaque
      stringData:
        key.pem: |
          -----BEGIN PRIVATE KEY-----
          -----END PRIVATE KEY-----
connectorConfig:
  enabled: true
  sharepoint:
    tenantId: d4a04d87-966a-4e28-a0d6-dcf7ce92490a
    baseUrl: https://uniqueapp.sharepoint.com
    sitesSource: config_file
    sites:
      - siteId: bd9c85ee-998f-4665-9c44-577cf5a08a66
        syncColumnName: FinanceGPTKnowledge
        ingestionMode: recursive
        scopeId: scope_example123456789
        storeInternally: enabled
        syncStatus: active
        syncMode: content_and_permissions
    auth:
      mode: certificate
      clientId: ff140e75-f52d-4312-b7ba-64d436895676
      privateKeyPath: /app/key.pem
      thumbprintSha1: 2fd4e1c67a2d28fced849ee1bb76e7391b93eb12
    graph:
      apiRateLimitPerMinute: 780000
  unique:
    authMode: cluster_local
    ingestionServiceBaseUrl: http://ingestion.unique:8091
    scopeManagementServiceBaseUrl: http://scope-management.unique:8094
    serviceExtraHeaders:
      x-company-id: "123456789101112131"
      x-user-id: "123456789101112131"
  processing:
    allowedMimeTypes:
      - application/pdf
    concurrency: 1