version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    cooldown:
      default-days: 14
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directories:
      - services/**/*
    cooldown:
      default-days: 14
    schedule:
      interval: monthly

  - package-ecosystem: helm
    directories:
      - services/**/*
    cooldown:
      default-days: 14
    schedule:
      interval: monthly

  - package-ecosystem: terraform
    directories:
      - services/**/*
    cooldown:
      default-days: 14
    schedule:
      interval: weekly
