# SPDX-SnippetBegin
# SPDX-License-Identifier: Apache License 2.0
# SPDX-SnippetCopyrightText: 2024 © Argo Project, argoproj/argo-helm
# SPDX-SnippetCopyrightText: 2024 © Unique AG
# SPDX-SnippetEnd
## Reference: https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md
# Don't add the 'debug' attribute, otherwise the workflow won't work anymore
# Only Used for the CT Lint Stage
chart-dirs: [services/sharepoint-connector/deploy/helm-charts, services/confluence-connector/deploy/helm-charts]
check-version-increment: false # release-please will handle this
exclude-deprecated: true
excluded-charts: []
remote: origin
target-branch: main
validate-chart-schema: false
validate-maintainers: false # TODO: enable if Artifact Hub is used
validate-yaml: true
additional-commands:
  - helm unittest {{ .Path }}
