## Reference: https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md
# Don't add the 'debug' attribute, otherwise the workflow won't work anymore
# Only Used for the CT Lint Stage
chart-dirs: [services/edgar-mcp/deploy/helm-charts]
check-version-increment: false # release-please will handle this
exclude-deprecated: true
excluded-charts: []
remote: origin
target-branch: main
validate-chart-schema: false
validate-maintainers: false # TODO: enable if Artifact Hub is used
validate-yaml: true
