connectorConfig:
  enabled: true
  confluence:
    instanceType: onprem
    baseUrl: https://confluence.acme.com
    auth:
      mode: basic
      username: admin
    apiRateLimitPerMinute: 50
  unique:
    authMode: cluster_local
    ingestionServiceBaseUrl: http://node-ingestion.finance-gpt:8091
    scopeManagementServiceBaseUrl: http://node-scope-management.finance-gpt:8094
    serviceExtraHeaders:
      x-company-id: "123456789101112131"
      x-user-id: "123456789101112131"
  processing:
    stepTimeoutSeconds: 600
    concurrency: 1
    scanIntervalCron: "0 */2 * * *"
