apiVersion: v2
name: mcp-server-factset
description: An experimental MCP server for Factset.
type: application
version: 0.2.4
appVersion: 0.2.4
dependencies:
  - alias: server
    name: backend-service
    repository: oci://ghcr.io/unique-ag/helm-charts
    version: ~5.4.2
