alerts:
  defaultAlerts:
    additionalLabels:
      team: data-flow
  enabled: true
connector:
  networkPolicy:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: system
        podSelector:
          matchLabels:
            app.kubernetes.io/managed-by: prometheus-operator
  prometheus:
    defaultAlerts:
      additionalLabels:
        team: data-flow
connectorConfig:
  sharepoint:
    apiRateLimitPerMinuteThousands: 180
    auth:
      clientId: 81154c31-c543-4458-811b-15245f48205b
      thumbprintSha1: 38E031FCDE64A24D9FF68B8783EF0397F7AECFA9
    baseUrl: https://dogfoodindustries.sharepoint.com
    sharepointList:
      listDisplayName: Sites to Sync
      siteId: af2b5be6-a37d-4992-ab8f-988b0134007e
    sitesSource: sharepoint_list
    tenantId: f96a6b77-d28b-491a-8bad-607af412b850
  unique:
    apiRateLimitPerMinute: 20
    ingestionServiceBaseUrl: http://node-ingestion.finance-gpt:8091
    scopeManagementServiceBaseUrl: http://node-scope-management.finance-gpt:8094
    serviceExtraHeaders:
      x-company-id: '225319369280852798'
      x-user-id: '335951437550850059'
grafana:
  dashboard:
    enabled: true
