{{- if .Values.connectorConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sharepoint-connector-proxy-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  PROXY_AUTH_MODE: {{ .Values.connectorConfig.proxy.authMode | quote }}
  {{- if ne .Values.connectorConfig.proxy.authMode "none" }}
  PROXY_HOST: {{ .Values.connectorConfig.proxy.host | quote }}
  PROXY_PORT: {{ .Values.connectorConfig.proxy.port | quote }}
  PROXY_PROTOCOL: {{ .Values.connectorConfig.proxy.protocol | quote }}
  {{- end }}
  {{- if eq .Values.connectorConfig.proxy.authMode "username_password" }}
  PROXY_USERNAME: {{ .Values.connectorConfig.proxy.username | quote }}
  {{- end }}
  {{- if eq .Values.connectorConfig.proxy.authMode "ssl_tls" }}
  PROXY_SSL_CERT_PATH: {{ .Values.connectorConfig.proxy.sslCertPath | quote }}
  PROXY_SSL_KEY_PATH: {{ .Values.connectorConfig.proxy.sslKeyPath | quote }}
  {{- end }}
  {{- if .Values.connectorConfig.proxy.sslCaBundlePath }}
  PROXY_SSL_CA_BUNDLE_PATH: {{ .Values.connectorConfig.proxy.sslCaBundlePath | quote }}
  {{- end }}
  {{- if .Values.connectorConfig.proxy.headers }}
  PROXY_HEADERS: {{ .Values.connectorConfig.proxy.headers | quote }}
  {{- end }}
{{- end }}
