apiVersion: v2
name: mcp-server-outlook
description: An experimental MCP server for Outlook leveraging the Microsoft Graph API.
type: application
version: 0.6.0
appVersion: 0.6.0
dependencies:
  - alias: server
    name: backend-service
    repository: oci://ghcr.io/unique-ag/helm-charts
    version: ~5.4.2
