apiVersion: v2
name: sharepoint-connector
description: Take content from SharePoint and send it to Unique AI for RAG ingestion.
type: application
version: 2.1.0
appVersion: 2.1.0
dependencies:
  - alias: connector
    name: backend-service
    repository: oci://ghcr.io/unique-ag/helm-charts
    version: ~10.2.0
