name: "[sharepoint-connector] Validate"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/services/sharepoint-connector/**"
      - .github/workflows/sharepoint-connector.ci.yaml

jobs:
  validate:
    uses: ./.github/workflows/_template-ci.yaml
    with:
      service-name: sharepoint-connector
      service-path: services/sharepoint-connector
      orm: none

  check_chart:
    runs-on: ubuntu-latest # TODO: can we use singularity here?
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          fetch-depth: 0 # we need the main branch as well
      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # 4.3.1
        with:
          version: v3.19.0

      - name: Setup Chart Linting
        id: lint
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # 2.7.0
        with:
          # Note: Also update in scripts/lint.sh
          version: v3.14.0

      - name: Render chart
        working-directory: services/sharepoint-connector/deploy/helm-charts/sharepoint-connector
        run: |
          helm dependency build
          helm template .

      - name: List changed charts
        id: list-changed
        run: |
          ## If executed with debug this won't work anymore.
          changed=$(ct --config ./.github/configs/ct-lint.yaml list-changed)
          charts=$(echo "$changed" | tr '\n' ' ' | xargs)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "changed_charts=$charts" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git
          ct lint --debug --config ./.github/configs/ct-lint.yaml --lint-conf ./.github/configs/lintconf.yaml

      - name: Create kind cluster
        uses: helm/kind-action@92086f6be054225fa813e0a4b13787fc9088faab # v1.13.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          config: .github/configs/kind-config.yaml

      - name: Deploy CRDs needed for charts to be able to install
        if: steps.list-changed.outputs.changed == 'true'
        run: ./scripts/setup-cluster.sh

      - name: Run chart-testing (install)
        run: ct install --config ./.github/configs/ct-install.yaml
        if: steps.list-changed.outputs.changed == 'true'

  check_terraform:
    runs-on: ubuntu-latest # TODO: can we use singularity here?
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # 3.1.2
        with:
          terraform_version: 1.13.4
      - name: validate sharepoint-connector-entra-application
        working-directory: services/sharepoint-connector/deploy/terraform/azure/sharepoint-connector-entra-application
        run: |
          terraform init
          terraform validate
      - name: validate sharepoint-connector-secrets
        working-directory: services/sharepoint-connector/deploy/terraform/azure/sharepoint-connector-secrets
        run: |
          terraform init
          terraform validate
