name: "[teams-mcp] Publish Docs to Confluence"

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:
  pull_request: # FIXME: remove before merge!
    paths:
      - .github/workflows/teams-mcp.docs.yaml
    branches:
      - main

jobs:
  publish-docs:
    uses: ./.github/workflows/_template-docs-confluence.yaml
    secrets: inherit
    with:
      service-name: teams-mcp
      docs-path: services/teams-mcp/docs
