name: "[mcp/server/teams] Validate"

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/services/teams-mcp/**"
      - .github/workflows/teams.server.mcp.ci.yaml

jobs:
  validate:
    uses: ./.github/workflows/_template-ci.yaml
    with:
      service-name: teams-mcp
      service-path: services/teams-mcp
      orm: drizzle
